生成启动时间为 2016/9/12 22:17:38。
     1>项目“E:\TestDemo\PyInterface\TestDllC\TestDllC.vcxproj”在节点 2 上(Build 个目标)。
     1>ClCompile:
         D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /IC:\Python35\include /ZI /nologo /W3 /WX- /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Yc"stdafx.h" /Fp"Debug\TestDllC.pch" /Fo"Debug\\" /Fd"Debug\vc110.pdb" /Gd /TP /analyze- /errorReport:prompt stdafx.cpp
         stdafx.cpp
         D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /IC:\Python35\include /ZI /nologo /W3 /WX- /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Yu"stdafx.h" /Fp"Debug\TestDllC.pch" /Fo"Debug\\" /Fd"Debug\vc110.pdb" /Gd /TP /analyze- /errorReport:prompt TestDllC.cpp
         TestDllC.cpp
       Link:
         D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\link.exe /ERRORREPORT:PROMPT /OUT:"E:\TestDemo\PyInterface\Debug\TestDllC.exe" /INCREMENTAL /NOLOGO /LIBPATH:C:\Python35\libs kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib python35.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:\TestDemo\PyInterface\Debug\TestDllC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:\TestDemo\PyInterface\Debug\TestDllC.lib" /MACHINE:X86 Debug\stdafx.obj
         Debug\TestDllC.obj
     1>LINK : fatal error LNK1104: 无法打开文件“python35_d.lib”
     1>已完成生成项目“E:\TestDemo\PyInterface\TestDllC\TestDllC.vcxproj”(Build 个目标)的操作 - 失败。

生成失败。

已用时间 00:00:01.16
